name: Add Users
on: workflow_dispatch

jobs:
  deploy:
    runs-on: [ self-hosted, cpu-server ]
    env:
      SUDO_PASSWD: ${{secrets.SUDO_PASSWD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run ansible playbook to add users
        run:  ansible-playbook -i user-management/hosts user-management/add-users.yml

      - name: Slack Notification on SUCCESS
        if: success()
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CHANGELOG_USERS_SHARED_SERVERS }}
        with:
          text: Add Users - Success.
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "GitHub URL",
                    "value": "${{ github.event.repository.url }}"
                  }
                ]
              }
            ]
      - name: Slack Notification on FAILURE
        if: failure()
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CHANGELOG_USERS_SHARED_SERVERS }}
        with:
          text: Add Users - Failure.
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "GitHub URL",
                    "value": "${{ github.event.repository.url }}"
                  }
                ]
              }
            ]